In [48]:
import pandas as pd
def avg_minute_per_game(df):
    df['MPA'] = df['MP'] / df['G']
    mpg = df.groupby("Tm", as_index = False)["MPA"].mean()
    return mpg
def true_shooting(df):
    TS = df.groupby("Tm",as_index = False)["TS%"].mean()
    return TS
def three_point_attempt(df):
    three = df.groupby("Tm",as_index = False)["3PAr"].mean()
    return three
def get_team_avg(df):
    m_p_g = avg_minute_per_game(df)
    ts = true_shooting(df)
    par = three_point_attempt(df)
    print("\n*****AVG Team Stats*****\n")
    
    print("\nAVERAGE MINUTE PER GAME IS:\n")
    print(m_p_g)

    print("\nTRUE SHOOTING AVERAGE IS:\n")
    print(ts)

    print("\n3-POINT ATTEMPT RATE AVERAGE IS:\n")
    print(par)
dtypes={"MP":int, "TS%":float, "3PAr":float}
df = pd.read_csv("nba.csv",dtype = dtypes)
choice = int(input("Input a number"))
if choice == 4:
    get_team_avg(df)

Input a number4

*****AVG Team Stats*****


AVERAGE MINUTE PER GAME IS:

     Tm        MPA
0   ATL  18.639045
1   BOS  17.211043
2   BRK  18.753117
3   CHI  20.463822
4   CHO  18.439538
5   CLE  20.113037
6   DAL  17.902487
7   DEN  19.255638
8   DET  18.455212
9   GSW  18.660188
10  HOU  18.226610
11  IND  16.527138
12  LAC  21.965471
13  LAL  18.619562
14  MEM  21.265657
15  MIA  19.955281
16  MIL  17.173943
17  MIN  18.385203
18  NOP  17.115763
19  NYK  18.719276
20  OKC  18.150439
21  ORL  20.497660
22  PHI  17.403353
23  PHO  20.877325
24  POR  18.687175
25  SAC  20.230159
26  SAS  18.567043
27  TOR  16.252597
28  TOT  16.977073
29  UTA  17.134979
30  WAS  20.538171

TRUE SHOOTING AVERAGE IS:

     Tm       TS%
0   ATL  0.544818
1   BOS  0.487650
2   BRK  0.527333
3   CHI  0.481143
4   CHO  0.537118
5   CLE  0.550409
6   DAL  0.491913
7   DEN  0.562941
8   DET  0.522545
9   GSW  0.553000
10  HOU  0.481792
11  IND  0.563824
12  LAC  0.560714
13  LAL  0.513958
14  MEM  0.523542
15  MIA  0.510421
16  MIL  0.537708
17  MIN  0.586938
18  NOP  0.491261
19  NYK  0.503429
20  OKC  0.541000
21  ORL  0.537211
22  PHI  0.527522
23  PHO  0.527409
24  POR  0.576812
25  SAC  0.506611
26  SAS  0.533647
27  TOR  0.595611
28  TOT  0.512492
29  UTA  0.564095
30  WAS  0.530933

3-POINT ATTEMPT RATE AVERAGE IS:

     Tm      3PAr
0   ATL  0.403682
1   BOS  0.428450
2   BRK  0.383619
3   CHI  0.383429
4   CHO  0.324882
5   CLE  0.350227
6   DAL  0.367130
7   DEN  0.351294
8   DET  0.318409
9   GSW  0.282235
10  HOU  0.445667
11  IND  0.257647
12  LAC  0.298476
13  LAL  0.348417
14  MEM  0.281667
15  MIA  0.433895
16  MIL  0.350208
17  MIN  0.284375
18  NOP  0.303957
19  NYK  0.261095
20  OKC  0.343412
21  ORL  0.334053
22  PHI  0.375913
23  PHO  0.339682
24  POR  0.282000
25  SAC  0.278222
26  SAS  0.292706
27  TOR  0.482722
28  TOT  0.329983
29  UTA  0.375286
30  WAS  0.258200